INSERT INTO COUNTRY
(COUNTRY_ID, COUNTRY_NAME, COUNTRY_CODE, CREATE_DATE, UPDATE_DATE)
VALUES
(14,'Andorra','AD', NOW(), NOW()),
(15,'United Arab Emirates','AE', NOW(), NOW()),
(16,'Afghanistan','AF', NOW(), NOW()),
(17,'Antigua & Barbuda','AG', NOW(), NOW()),
(18,'Anguilla','AI', NOW(), NOW()),
(19,'Albania','AL', NOW(), NOW()),
(20,'Armenia','AM', NOW(), NOW()),
(21,'Netherlands Antilles','AN', NOW(), NOW()),
(22,'Angola','AO', NOW(), NOW()),
(23,'Antarctica','AQ', NOW(), NOW()),
(24,'Argentina','AR', NOW(), NOW()),
(25,'American Samoa','AS', NOW(), NOW()),
(26,'Austria','AT', NOW(), NOW()),
(27,'Australia','AU', NOW(), NOW()),
(28,'Aruba','AW', NOW(), NOW()),
(29,'Azerbaijan','AZ', NOW(), NOW()),
(30,'Bosnia & Herzegowina','BA', NOW(), NOW()),
(31,'Barbados','BB', NOW(), NOW()),
(32,'Bangladesh','BD', NOW(), NOW()),
(33,'Belgium','BE', NOW(), NOW()),
(34,'Bulgaria','BG', NOW(), NOW()),
(35,'Bahrain','BH', NOW(), NOW()),
(36,'Burundi','BI', NOW(), NOW()),
(37,'Benin','BJ', NOW(), NOW()),
(38,'Bermuda','BM', NOW(), NOW()),
(39,'Brunei Darussalam','BN', NOW(), NOW()),
(40,'Bolivia','BO', NOW(), NOW()),
(41,'Brazil','BR', NOW(), NOW()),
(42,'Bahamas','BS', NOW(), NOW()),
(43,'Bhutan','BT', NOW(), NOW()),
(44,'Bouvet Island','BV', NOW(), NOW()),
(45,'Botswana','BW', NOW(), NOW()),
(46,'Belarus','BY', NOW(), NOW()),
(47,'Belize','BZ', NOW(), NOW()),
(48,'Canada','CA', NOW(), NOW()),
(49,'Cocos Keeling Isla','CC', NOW(), NOW()),
(50,'Dem. Repub. of Congo','CD', NOW(), NOW()),
(51,'Channel Islands',NULL, NOW(), NOW()),
(52,'Central African Repu','CF', NOW(), NOW()),
(53,'Congo','CG', NOW(), NOW()),
(54,'Switzerland','CH', NOW(), NOW()),
(55,'Ivory Coast','CI', NOW(), NOW()),
(56,'Cook Islands','CK', NOW(), NOW()),
(57,'Chile','CL', NOW(), NOW()),
(58,'Cameroon','CM', NOW(), NOW()),
(59,'China','CN', NOW(), NOW()),
(60,'Colombia','CO', NOW(), NOW()),
(61,'Costa Rica','CR', NOW(), NOW()),
(62,'Cuba','CU', NOW(), NOW()),
(63,'Cape Verde','CV', NOW(), NOW()),
(64,'Christmas Island','CX', NOW(), NOW()),
(65,'Cyprus','CY', NOW(), NOW()),
(66,'Czech Republic','CZ', NOW(), NOW()),
(67,'Germany','DE', NOW(), NOW()),
(68,'Djibouti','DJ', NOW(), NOW()),
(69,'Denmark','DK', NOW(), NOW()),
(70,'Dominica','DM', NOW(), NOW()),
(71,'Dominican Republic','DO', NOW(), NOW()),
(72,'Algeria','DZ', NOW(), NOW()),
(73,'Ecuador','EC', NOW(), NOW()),
(74,'Estonia','EE', NOW(), NOW()),
(75,'Egypt','EG', NOW(), NOW()),
(76,'Western Sahara','EH', NOW(), NOW()),
(77,'Eritrea','ER', NOW(), NOW()),
(78,'Spain','ES', NOW(), NOW()),
(79,'Ethiopia','ET', NOW(), NOW()),
(80,'Europe','EU', NOW(), NOW()),
(81,'Finland','FI', NOW(), NOW()),
(82,'Fiji','FJ', NOW(), NOW()),
(83,'Falkland Islands Ma','FK', NOW(), NOW()),
(84,'Federated Micronesia','FM', NOW(), NOW()),
(85,'Faroe Islands','FO', NOW(), NOW()),
(86,'France','FR', NOW(), NOW()),
(88,'Gabon','GA', NOW(), NOW()),
(89,'United Kingdom','GB', NOW(), NOW()),
(90,'Grenada','GD', NOW(), NOW()),
(91,'Georgia','GE', NOW(), NOW()),
(92,'French Guiana','GF', NOW(), NOW()),
(93,'Ghana','GH', NOW(), NOW()),
(94,'Gibraltar','GI', NOW(), NOW()),
(95,'Greenland','GL', NOW(), NOW()),
(96,'Gambia','GM', NOW(), NOW()),
(97,'Guinea','GN', NOW(), NOW()),
(98,'Guadeloupe','GP', NOW(), NOW()),
(99,'Equatorial Guinea','GQ', NOW(), NOW()),
(100,'Greece','GR', NOW(), NOW()),
(101,'South Georgia & Sout','GS', NOW(), NOW()),
(102,'Guatemala','GT', NOW(), NOW()),
(103,'Guam','GU', NOW(), NOW()),
(104,'Guyana','GY', NOW(), NOW()),
(105,'Guernsey','GG', NOW(), NOW()),
(106,'Hong Kong','HK', NOW(), NOW()),
(107,'Heard & Mc Donald Is','HM', NOW(), NOW()),
(108,'Honduras','HN', NOW(), NOW()),
(109,'Croatia','HR', NOW(), NOW()),
(110,'Haiti','HT', NOW(), NOW()),
(111,'Hungary','HU', NOW(), NOW()),
(112,'Indonesia','ID', NOW(), NOW()),
(113,'Ireland','IE', NOW(), NOW()),
(115,'Israel','IL', NOW(), NOW()),
(116,'Isle of Man','IM', NOW(), NOW()),
(117,'India','IN', NOW(), NOW()),
(118,'British Indian Ocean','IO', NOW(), NOW()),
(119,'Iraq','IQ', NOW(), NOW()),
(120,'Iran','IR', NOW(), NOW()),
(121,'Iceland','IS', NOW(), NOW()),
(122,'Italy','IT', NOW(), NOW()),
(123,'Jersey','JE', NOW(), NOW()),
(124,'Jamaica','JM', NOW(), NOW()),
(125,'Jordan','JO', NOW(), NOW()),
(126,'Japan','JP', NOW(), NOW()),
(127,'Kenya','KE', NOW(), NOW()),
(128,'Kyrgyzstan','KG', NOW(), NOW()),
(129,'Cambodia','KH', NOW(), NOW()),
(130,'Kiribati','KI', NOW(), NOW()),
(131,'Comoros','KM', NOW(), NOW()),
(132,'Saint Kitts & Nevis','KN', NOW(), NOW()),
(133,'North Korea','KP', NOW(), NOW()),
(134,'South Korea','KR', NOW(), NOW()),
(135,'Kuwait','KW', NOW(), NOW()),
(136,'Cayman Islands','KY', NOW(), NOW()),
(137,'Kazakhstan','KZ', NOW(), NOW()),
(138,'Laos','LA', NOW(), NOW()),
(139,'Lebanon','LB', NOW(), NOW()),
(140,'Saint Lucia','LC', NOW(), NOW()),
(141,'Liechtenstein','LI', NOW(), NOW()),
(142,'Sri Lanka','LK', NOW(), NOW()),
(143,'Liberia','LR', NOW(), NOW()),
(144,'Lesotho','LS', NOW(), NOW()),
(145,'Lithuania','LT', NOW(), NOW()),
(146,'Luxembourg','LU', NOW(), NOW()),
(147,'Latvia','LV', NOW(), NOW()),
(148,'Libya','LY', NOW(), NOW()),
(149,'Morocco','MA', NOW(), NOW()),
(150,'Monaco','MC', NOW(), NOW()),
(151,'Moldova','MD', NOW(), NOW()),
(152,'Madagascar','MG', NOW(), NOW()),
(153,'Marshall Islands','MH', NOW(), NOW()),
(154,'Macedonia','MK', NOW(), NOW()),
(155,'Mali','ML', NOW(), NOW()),
(156,'Myanmar','MM', NOW(), NOW()),
(157,'Mongolia','MN', NOW(), NOW()),
(158,'Macau','MO', NOW(), NOW()),
(159,'Northern Mariana Isl','MP', NOW(), NOW()),
(160,'Martinique','MQ', NOW(), NOW()),
(161,'Mauritania','MR', NOW(), NOW()),
(162,'Montserrat','MS', NOW(), NOW()),
(163,'Malta','MT', NOW(), NOW()),
(164,'Mauritius','MU', NOW(), NOW()),
(165,'Maldives','MV', NOW(), NOW()),
(166,'Malawi','MW', NOW(), NOW()),
(167,'Mexico','MX', NOW(), NOW()),
(168,'Malaysia','MY', NOW(), NOW()),
(169,'Mozambique','MZ', NOW(), NOW()),
(170,'Namibia','NA', NOW(), NOW()),
(171,'New Caledonia','NC', NOW(), NOW()),
(172,'Niger','NE', NOW(), NOW()),
(173,'Norfolk Island','NF', NOW(), NOW()),
(174,'Nigeria','NG', NOW(), NOW()),
(175,'Nicaragua','NI', NOW(), NOW()),
(176,'Netherlands','NL', NOW(), NOW()),
(177,'Norway','NO', NOW(), NOW()),
(178,'Nepal','NP', NOW(), NOW()),
(179,'Nauru','NR', NOW(), NOW()),
(180,'Niue','NU', NOW(), NOW()),
(181,'New Zealand','NZ', NOW(), NOW()),
(182,'Oman','OM', NOW(), NOW()),
(184,'Panama','PA', NOW(), NOW()),
(185,'Peru','PE', NOW(), NOW()),
(186,'French Polynesia','PF', NOW(), NOW()),
(187,'Papua New Guinea','PG', NOW(), NOW()),
(188,'Philippines','PH', NOW(), NOW()),
(189,'Pakistan','PK', NOW(), NOW()),
(190,'Poland','PL', NOW(), NOW()),
(191,'St. Pierre & Miquelo','PM', NOW(), NOW()),
(192,'Pitcairn','PN', NOW(), NOW()),
(193,'Puerto Rico','PR', NOW(), NOW()),
(194,'Palestine','PS', NOW(), NOW()),
(195,'Portugal','PT', NOW(), NOW()),
(196,'Palau','PW', NOW(), NOW()),
(197,'Paraguay','PY', NOW(), NOW()),
(198,'Qatar','QA', NOW(), NOW()),
(199,'Reunion','RE', NOW(), NOW()),
(200,'Romania','RO', NOW(), NOW()),
(201,'Russian Fed.','RU', NOW(), NOW()),
(202,'Rwanda','RW', NOW(), NOW()),
(203,'Serbia & Mont','RS', NOW(), NOW()),
(204,'Saudi Arabia','SA', NOW(), NOW()),
(205,'Solomon Islands','SB', NOW(), NOW()),
(206,'Seychelles','SC', NOW(), NOW()),
(207,'Sudan','SD', NOW(), NOW()),
(208,'Sweden','SE', NOW(), NOW()),
(209,'Singapore','SG', NOW(), NOW()),
(210,'St. Helena','SH', NOW(), NOW()),
(211,'Slovenia','SI', NOW(), NOW()),
(212,'Svalbard & Jan Mayen','SJ', NOW(), NOW()),
(213,'Slovakia','SK', NOW(), NOW()),
(214,'Sierra Leone','SL', NOW(), NOW()),
(215,'San Marino','SM', NOW(), NOW()),
(216,'Senegal','SN', NOW(), NOW()),
(217,'Somalia','SO', NOW(), NOW()),
(218,'Suriname','SR', NOW(), NOW()),
(219,'Sao Tome & Principe','ST', NOW(), NOW()),
(220,'El Salvador','SV', NOW(), NOW()),
(221,'Syria','SY', NOW(), NOW()),
(222,'Swaziland','SZ', NOW(), NOW()),
(223,'Turks & Caicos Islan','TC', NOW(), NOW()),
(224,'Chad','TD', NOW(), NOW()),
(225,'French Southern Terr','TF', NOW(), NOW()),
(226,'Togo','TG', NOW(), NOW()),
(227,'Thailand','TH', NOW(), NOW()),
(228,'Tajikistan','TJ', NOW(), NOW()),
(229,'Tokelau','TK', NOW(), NOW()),
(230,'Turkmenistan','TM', NOW(), NOW()),
(231,'Tunisia','TN', NOW(), NOW()),
(232,'Tonga','TO', NOW(), NOW()),
(233,'East Timor','TL', NOW(), NOW()),
(234,'Turkey','TR', NOW(), NOW()),
(235,'Trinidad & Tobago','TT', NOW(), NOW()),
(236,'Tuvalu','TV', NOW(), NOW()),
(237,'Taiwan','TW', NOW(), NOW()),
(238,'Tanzania','TZ', NOW(), NOW()),
(239,'Ukraine','UA', NOW(), NOW()),
(240,'Uganda','UG', NOW(), NOW()),
(241,'United States','US', NOW(), NOW()),
(242,'Uruguay','UY', NOW(), NOW()),
(243,'Uzbekistan','UZ', NOW(), NOW()),
(244,'Vatican City','VA', NOW(), NOW()),
(246,'Venezuela','VE', NOW(), NOW()),
(248,'Virgin Islands UK','VG', NOW(), NOW()),
(249,'Viet Nam','VN', NOW(), NOW()),
(250,'Vanuatu','VU', NOW(), NOW()),
(251,'Wallis & Futuna Isla','WF', NOW(), NOW()),
(252,'Yemen','YE', NOW(), NOW()),
(253,'Mayotte','YT', NOW(), NOW()),
(254,'Yugoslavia','YU', NOW(), NOW()),
(255,'South Africa','ZA', NOW(), NOW()),
(256,'Zambia','ZM', NOW(), NOW()),
(257,'Zaire','ZR', NOW(), NOW()),
(258,'Zimbabwe','ZW', NOW(), NOW()),
(265,'Virgin Islands US','VI', NOW(), NOW()),
(276,'Burkina Faso','BF', NOW(), NOW()),
(337,'Czechoslovakia','Cs', NOW(), NOW()),
(338,'Wight','WI', NOW(), NOW()),
(341,'Other','OT', NOW(), NOW()),
(342,'Saint Vincent & the','VC', NOW(), NOW());